### ISSUE TITLE
Invalid error thrown by browser.goTo

### ISSUE THREAD

**Issue by nair-sumesh** [js-soft/wdi5#148]
**Describe the bug**
`browser.goTo` does not navigate to Shell-home

**To Reproduce**
  async iNavigateToHomePage() {
    await browser.goTo({ sHash: '#Shell-home' });
  }

**Expected behavior**
Supposed to Navigate to the shell home (Fiori launchpad page)

**Logs/Console Output**
```shell
[0-0] Error in "test.I reopen app"
Error: Invalid URL: #Shell-home
    at validateUrl (C:\Users\nnnnnn\git\wdi5-testing\node_modules\webdriverio\build\utils\index.js:378:45)
    at Browser.url (C:\Users\nnnnnn\git\wdi5-testing\node_modules\webdriverio\build\commands\browser\url.js:47:52)
    at Browser.wrapCommandFn (C:\Users\nnnnnn\git\wdi5-testing\node_modules\@wdio\utils\build\shim.js:137:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Browser.<anonymous> (C:\Users\nnnnnn\git\wdi5-testing\node_modules\wdio-ui5-service\src\lib\wdioUi5-index.js:483:17)
    at Browser.wrapCommandFn (C:\Users\nnnnnn\git\wdi5-testing\node_modules\@wdio\utils\build\shim.js:137:29)
```

**Runtime Env (please complete the following information):**
- `wdi5/wdio-ui5-service`-version: 0.8.2
- `UI5` version: [1.99.0-SNAPSHOT]
- `wdio`-version (output of `wdio --version`): 7.16.15
- `node`-version (output of `node --version`): 16.13.2
 - OS: Win 10
 - Browser + Version : chrome (v98.0.4758.82) on Windows

**Comment by vobu** [comment]
the command itself is syntactically correct (`browser.goTo({ sHash: '#Shell-home' })`)
might be a problem with your configuration.
can you share your `wdio.config.(j|t)s`-file please? "`baseUrl`" and the "`wdi5`" should be sufficient.

**Comment by nair-sumesh** [comment]
```json
  wdi5: {
    screenshotPath: path.join('wdio-ui5-service', 'test', 'report', 'screenshots'),
    logLevel: 'verbose', // error | verbose | silent
    platform: 'browser', // electron, browser, android, ios
    url: '',
    skipInjectUI5OnStart: true,
    deviceType: 'web',
    waitForUI5Timeout: 15000
  },

...
baseUrl :''
```

Later in the before() method, I call await browser.url(sURL);
where sURL is dynamically generated.

**Comment by vobu** [comment]
oi, the empty `baseUrl` is most likely the culprit. Try providing that, please
