### ISSUE TITLE
Cannot retrieve control due to timeout in puppeteer (regression

### ISSUE THREAD

**Issue by laszlo-szentes** [js-soft/wdi5#266]
**Describe the bug**
Tests specs fail to obtain the very fist control, which happens to be a Fiori tile, in order to start our application(s). Consequently, all test cases will fail. 

Same code works with version `0.9.0-rc3`.

**To Reproduce**

```shell

```

**Expected behavior**

**Logs/Console Output**

```shell
Evaluation failed: script timeout
Error: Evaluation failed: script timeout
    at ExecutionContext._evaluateInternal (/home/i070292/SAPDevelop/eps/apps/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (/home/i070292/SAPDevelop/eps/apps/node_modules/puppeteer-core/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async ElementHandle.evaluate (/home/i070292/SAPDevelop/eps/apps/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:107:16)
    at async ElementHandle.$eval (/home/i070292/SAPDevelop/eps/apps/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:810:24)
    at async DevToolsDriver.executeAsyncScript (/home/i070292/SAPDevelop/eps/apps/node_modules/devtools/build/commands/executeAsyncScript.js:31:20)
    at async Browser.wrappedCommand (/home/i070292/SAPDevelop/eps/apps/node_modules/devtools/build/devtoolsdriver.js:102:26)
    at async clientSide_executeControlMethod (/home/i070292/SAPDevelop/eps/apps/node_modules/wdio-ui5-service/client-side-js/executeControlMethod.js:2:12)
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.1
- `UI5` version: 1.98.0
- `wdio`-version (output of `wdio --version`): 7.19.7
- `node`-version (output of `node --version`): v16.13.0
- OS: Windows 10
- Browser + Version: Chrome 100.0.4896.127

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by laszlo-szentes** [comment]
Created accidentally, there's a final version, therefore closing this one.
