### ISSUE TITLE
No 'inputToValidate' given but it is a mandatory parameter

### ISSUE THREAD

**Issue by nilskasseckert** [js-soft/wdi5#73]
I am currently trying to integrate WDI5 into my project. Currently WDIO is started via the web browser.

The start page is the Fiori Launchpad. Then I navigate to the app using `browser.goTo({sHash:` `'#MyFioriObject-display'});`.

Now I just want to get a control at the beginning. For this I wrote the following code. 
```
    const oSelector = { 
        selector: {
            id: 'input',
            controlType: 'sap.m.Input'
        }
    };
 
    const control = browser.asControl(oSelector);
```

I already tried to add the view or to try other elements but I always get the following error. I even get the error if I want to get an button or an view.

> Evaluation failed: Error: sap.ui.test.autowaiter._autoWaiterAsync#extendConfig - No 'inputToValidate' given but it is a mandatory parameter
    at _validate (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/_ParameterValidator.js?eval:6:509)
    at _.validate (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/_ParameterValidator.js?eval:6:371)
    at v (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/autowaiter/_autoWaiterAsync.js?eval:6:1253)
    at Object.e [as extendConfig] (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/autowaiter/_autoWaiterAsync.js?eval:6:466)
    at Function.R.waitForUI5 (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/RecordReplay.js?eval:6:1935)
    at eval (eval at <anonymous> (:20:16), <anonymous>:3:18)
    at eval (eval at <anonymous> (:20:16), <anonymous>:24:12)
    at __puppeteer_evaluation_script__:20:16
    at __puppeteer_evaluation_script__:2:12
Error: Evaluation failed: Error: sap.ui.test.autowaiter._autoWaiterAsync#extendConfig - No 'inputToValidate' given but it is a mandatory parameter
    at ExecutionContext._evaluateInternal (XXX\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async ExecutionContext.evaluate (XXX\node_modules\puppeteer-core\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
    at async ElementHandle.evaluate (XXX\node_modules\puppeteer-core\lib\cjs\puppeteer\common\JSHandle.js:102:16)
    at async ElementHandle.$eval (XXX\node_modules\puppeteer-core\lib\cjs\puppeteer\common\JSHandle.js:650:24)
    at async DevToolsDriver.executeAsyncScript (XXX\node_modules\devtools\build\commands\executeAsyncScript.js:19:20)
    at async Browser.wrappedCommand (XXX\node_modules\devtools\build\devtoolsdriver.js:62:26)
    at async Browser.runCommandWithHooks (XXX\node_modules\@wdio\sync\build\wrapCommand.js:70:25)
    at Browser.runCommandWithHooks (XXX\node_modules\@wdio\sync\build\wrapCommand.js:65:24)
    at Browser.wrapCommandFn (XXX\node_modules\@wdio\sync\build\wrapCommand.js:44:44)
    at Browser.executeAsync (XXX\node_modules\webdriverio\build\commands\browser\executeAsync.js:11:17)
    at Browser.runCommandWithHooks (XXX\node_modules\@wdio\sync\build\wrapCommand.js:70:34)
    at WDI5._getControl (XXX\node_modules\wdio-ui5-service\src\lib\WDI5.js:508:32)
    at new WDI5 (XXX\node_modules\wdio-ui5-service\src\lib\WDI5.js:36:36)
    at Browser.<anonymous> (XXX\node_modules\wdio-ui5-service\src\lib\wdioUi5-index.js:467:33)
    at XXX\node_modules\@wdio\sync\build\runFnInFiberContext.js:13:35
    at Browser.asControl (XXX\node_modules\@wdio\sync\build\wrapCommand.js:44:44)
    at Browser.next [as asControl] (XXX\node_modules\@wdio\utils\build\monad.js:95:33)
    at World.<anonymous> (XXX\webapp\test\steps\Test.js:27:29)
    at World.executeSync (XXX\node_modules\@wdio\sync\build\index.js:25:22)
    at XXX\node_modules\@wdio\sync\build\index.js:46:68

Why and how can I fix it?

Thanks in advance!

Regards,
Nils

**Comment by vobu** [comment]
hi, upfront: never encountered a similar error so far.
`selector`-wise this looks fine and translates to: "look across all views for a `sap.m.Input` with id `input`".
i'll quickly run the `wdi5`-internal tests against the UI5 version 1.60.31 you're using and see what i get.

**Comment by vobu** [comment]
- 1.86.3: ✅ 
- 1.77.2: ✅ 
- 1.76.0: ✅ 
- 1.75.7: ✅ 
- 1.74.0: ✅ 
- 1.73.2: ✅ 
- 1.72.7: ✅ 
- 1.71.25: 🚫 
- 1.70.0: ✅ 
- 1.60.31: 🚫 

this indicates that `sap.ui.test.autowaiter.*` might be the culprit in 1.60.x
again, let me dive into our codebase and get back here

**Comment by vobu** [comment]
alright, found the culprit: in some versions of UI5, the internal `RecordReplay.waitForUI5()` wants a default options object.
we'll enhance `wdi5` and release a new version asap

**Comment by nilskasseckert** [comment]
Hi @vobu 

thanks a lot for the really quick fix and the the continuous updates!

**Comment by vobu** [comment]
@nilskasseckert please double-check w/ 0.5.1

**Comment by nilskasseckert** [comment]
Hi @vobu 
thank you very much! It work.
