### ISSUE TITLE
Take Screenshots Crashs with waitForUI5 of undefined

### ISSUE THREAD

**Issue by nilskasseckert** [js-soft/wdi5#75]
Hello,
we want to use WDI5 for our tests with Cucumber. For this we have built a relatively simple test setup. First the launchpad is started and then the app is to be loaded.

This works fine locally. Unfortunately, in the pipeline the app is not loaded and therefore the browser title does not change. To better analyze the problem we wanted to try the screenshot function of WDI5. Unfortunately, this immediately crashes with the following error. The screenshot function is locally and in the pipeline not working.

Why? What are we doing wrong?

Thanks and best regards
Nils

Error log:
```
2021-04-07T10:23:22.556Z DEBUG @wdio/utils:initialiseServices: initialise service "ui5" as NPM package
2021-04-07T10:23:22.567Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-04-07T10:23:22.568Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 0ms
2021-04-07T10:23:22.569Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-04-07T10:23:22.569Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2021-04-07T10:23:22.570Z INFO @wdio/local-runner: Start worker 0-0 with arg: 
[0-0] 2021-04-07T10:23:23.315Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-04-07T10:23:23.534Z DEBUG @wdio/config:utils: Found 'ts-node' package, auto-compiling TypeScript files
[0-0] 2021-04-07T10:23:23.537Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-04-07T10:23:23.543Z DEBUG @wdio/utils:initialiseServices: initialise service "ui5" as NPM package

.....

[0-0] 2021-04-07T10:23:30.344Z DEBUG @wdio/local-runner:utils: init remote session
[0-0] 2021-04-07T10:23:30.345Z INFO devtools:puppeteer: Initiate new session using the DevTools protocol
[0-0] 2021-04-07T10:23:30.346Z INFO devtools: Launch Google Chrome with flags: --enable-automation --disable-popup-blocking --disable-extensions --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-first-run --no-default-browser-check --disable-hang-monitor --disable-prompt-on-repost --disable-client-side-phishing-detection --password-store=basic --use-mock-keychain --disable-component-extensions-with-background-pages --disable-breakpad --disable-dev-shm-usage --disable-ipc-flooding-protection --disable-renderer-backgrounding --force-fieldtrials=*BackgroundTracing/default/ --enable-features=NetworkService,NetworkServiceInProcess --disable-features=site-per-process,TranslateUI,BlinkGenPropertyTrees --window-position=0,0 --window-size=1200,900 --headless --disable-gpu --no-sandbox --disable-dev-shm-usage --disable-browser-side-navigation --window-size=1920,1080
[0-0] 2021-04-07T10:23:30.911Z INFO devtools: Connect Puppeteer with browser on port 50172
[0-0] open url with fallback (this is not causing any issues since its is removed for navigation): #
[0-0] 2021-04-07T10:23:31.113Z INFO devtools: COMMAND navigateTo("http://localhost:3000/#")
[0-0] 2021-04-07T10:23:34.190Z INFO devtools: RESULT null
[0-0] wdio-ui5-service before hook
[0-0] creating internal control map
[0-0] 2021-04-07T10:23:34.194Z INFO devtools: COMMAND executeAsyncScript("return ((done) => {
                setTimeout(() => {
                    if (document.location.href != 'data:,') {
                        // make sure we are not on the initial page
                        done(document.readyState);
                    }
                }, 400);
            }).apply(null, arguments)", <object>)
[0-0] 2021-04-07T10:23:35.114Z INFO devtools: RESULT complete
[0-0] 2021-04-07T10:23:35.151Z INFO devtools: COMMAND executeScript("return (() => {
        // browser context - you may not access client or console
        return !!window.sap;
    }).apply(null, arguments)", <object>)
[0-0] 2021-04-07T10:23:35.168Z INFO devtools: RESULT true
[0-0] sucessfully initialized wdio-ui5 bridge
[0-0] 2021-04-07T10:23:35.170Z DEBUG @wdio/sync: Finished to run "before" hook in 4061ms

.....

[0-0] 2021-04-07T10:23:49.312Z INFO webdriver: COMMAND screenshot("some-id")
[0-0] 2021-04-07T10:23:49.317Z INFO devtools: COMMAND executeAsyncScript("return ((done) => {
            window.bridge
                .waitForUI5()
                .then(() => {
                    window.wdi5.Log.info('[browser wdi5] UI5 is ready');
                    done(true);
                })
                .catch((error) => {
                    console.error(error);
                });
        }).apply(null, arguments)", <object>)
[0-0] Error in "0: die App geladen ist"
waitUntil condition failed with the following reason: Evaluation failed: TypeError: Cannot read property 'waitForUI5' of undefined
    at eval (eval at <anonymous> (:20:16), <anonymous>:3:18)
    at eval (eval at <anonymous> (:20:16), <anonymous>:11:12)
    at __puppeteer_evaluation_script__:20:16
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:2:12
Error: waitUntil condition failed with the following reason: Evaluation failed: TypeError: Cannot read property 'waitForUI5' of undefined
    at eval (eval at <anonymous> (:20:16), <anonymous>:3:18)
    at eval (eval at <anonymous> (:20:16), <anonymous>:11:12)
    at __puppeteer_evaluation_script__:20:16
    at __puppeteer_evaluation_script__:2:12
    at /..../node_modules/webdriverio/src/commands/browser/waitUntil.ts:79:15
    at World.<anonymous> 

```

Our wdio.conf.js is the following:
```
const dynamicConfig = {};

if (process.env.CI) {
    dynamicConfig.port = 9515;
    dynamicConfig.path = '/';
    dynamicConfig.services = ["chromedriver", "ui5"];
} else {
    dynamicConfig.automationProtocol = "devtools";
    dynamicConfig.services = ["ui5"];
}

exports.config = Object.assign({},{

    runner: 'local',

    specs: [
        './features/**/*.feature'
    ],

    maxInstances: 1,
    capabilities: [{
        browserName: 'chrome',
        'goog:chromeOptions': {
            args: ['--headless', '--disable-gpu',
                   '--no-sandbox', '--disable-dev-shm-usage',
                   '--disable-browser-side-navigation', '--window-size=1920,1080']
        },
        acceptInsecureCerts: true
    }],

    bail: 0,

    baseUrl: 'http://localhost:3000/',

    waitforTimeout: 10000,

    connectionRetryTimeout: 120000,

    connectionRetryCount: 3,

    framework: 'cucumber',
    reporters: ['spec',
        ['junit', {
            outputDir: "./0_wdioTestResults",
            outputFileFormat: function (options) {
                return `results-${options.cid}.xml`;
            }
        }]
    ],

    cucumberOpts: {
        // <string[]> (file/dir) require files before executing features
        require: ['./webapp/test/steps/**/*.js'],
        // <boolean> show full backtrace for errors
        backtrace: true,
        // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        requireModule: [],
        // <boolean> invoke formatters without executing steps
        dryRun: false,
        // <boolean> abort the run on first failure
        failFast: false,
        // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        format: ['pretty'],
        // <boolean> hide step definition snippets for pending steps
        snippets: true,
        // <boolean> hide source uris
        source: true,
        // <string[]> (name) specify the profile to use
        profile: [],
        // <boolean> fail if there are any undefined or pending steps
        strict: false,
        // <string> (expression) only execute the features or scenarios with tags matching the expression
        tagExpression: '',
        // <number> timeout for step definitions
        timeout: 60000,
        // <boolean> Enable this config to treat undefined definitions as warnings.
        ignoreUndefinedDefinitions: false
    },

    wdi5: {
        screenshotPath: './screenshots/', // [optional] using the project root
        screenshotsDisabled: false,
        logLevel: 'trace',
        platform: 'browser', // [mandatory] browser | android | ios | electron
        url: '', // [mandatory, not empty] path to your bootstrap html file. If your server autoredirects to a 'domain:port/' like root url use empty string ''
        deviceType: 'web', // [mandatory] native | web
        skipInjectUI5OnStart: false // [optional] true when UI5 is not on the start page, you need to later call <wdioUI5service>.injectUI5(); manually
    },

    beforeSession: function (config, capabilities, specs) {
        //Start Testserver
    },

    beforeFeature: function (uri, feature, scenarios) {
        browser.url("/");
        const pageTitle = browser.getTitle();
        if (pageTitle !== 'sLokales Launchpad') {
            console.error(`Fiori Launchpad is not up, found ${pageTitle}`);
            console.log(browser.getPageSource());
            process.exit(1);
        }
    },
    afterSession: function (config, capabilities, specs) {
        //Kill Testserver
    }
}, dynamicConfig);
```

The step implementation the following:
```
const { Given, When, Then } = require('@cucumber/cucumber');

Given(/Ich starte die App/, function() {
    browser.url("#MyFioriObject-display");
    browser.refresh();
});

When(/die App geladen ist/, function() {
    browser.waitUntil( () => {
        browser.screenshot('some-id');
        return browser.getTitle() === "MyAppName";
```

**Comment by vobu** [comment]
quick guesstimate: in your test, `Given` seems to refresh the browser -> so you'd need to re-inject `wdi5` again like
```js
// only requiring the service for late inject/init
const _ui5Service = require('wdio-ui5-service').default;
const ui5Service = new _ui5Service();

Given(/Ich starte die App/, function() {
    browser.url("#MyFioriObject-display");
    browser.refresh();
});

When(/die App geladen ist/, function() {
     //  (might work here as well, not sure)
    // ui5Service.injectUI5();
    browser.waitUntil( () => {
        //  re-inject after browser.refresh
        ui5Service.injectUI5();
        browser.screenshot('some-id');
        return browser.getTitle() === "MyAppName";
```

hth, v.

**Comment by dominikfeininger** [comment]
Hi Nils, 
can you please confirm you open a valid url with index file. See wdi5 your empty config parameter url.
`url: '', // [mandatory, not empty] path to your bootstrap html file. If your server autoredirects to a 'domain:port/' like root url use empty string ''`
For easier issue identification remove the `--headless` parameter from chrome startup options.

**Comment by vobu** [comment]
> Hi Nils,
> can you please confirm you open a valid url with index file. See wdi5 your empty config parameter url.
> `url: '', // [mandatory, not empty] path to your bootstrap html file. If your server autoredirects to a 'domain:port/' like root url use empty string ''`
> For easier issue identification remove the `--headless` parameter from chrome startup options.

haha, "erster" :)

**Comment by nilskasseckert** [comment]
Hallo zusammen,

da können wir ja auf Deutsch weiter machen, wenn es für euch passt 👍 

Auf localhost:3000 wird das Launchpad gestartet. Vom Prinzip her dasselbe wie beim UI5-Tooling über UI5 Serve nur halt auf Port 3000. Sprich da kommt ein Launchpad. 

Headless habe ich entfernt. Sieht alles normal aus und lokal navigiert der ja auch. Das refresh hab ich extra mal weggenommen. Ändert leider am Verhalten nichts. 

Viele Grüße
Nils

**Comment by vobu** [comment]
just a notice: let's switch back to English. As this might be of interest to other non-German speakers running into a similar problem

**Comment by vobu** [comment]
just a hunch: any reason why you're wrapping the `browser.screenshot(...)` into a `browser.waitUntil()`?
`wdi5` uses the same sync approach in coding as wdio, so you  could just do 
```js
When(/die App geladen ist/, function() {
        browser.screenshot('some-id');
        expect(browser.getTitle()).toStrictEqual("MyAppName");
}
```

**Comment by nilskasseckert** [comment]
Hi @vobu 
yes. The reason is that I want to wait until the Page is loaded. This needs some time until the Navigation from Launchpad to App is done and the App is fully loaded.

Regards,
Nils

**Comment by dominikfeininger** [comment]
Seems like the framework initialisation fails. (Note to myself: "improve error handling"). The `window.bridge` should contain `sap.ui.test.RecordReplay` (https://openui5.hana.ondemand.com/api/sap.ui.test.RecordReplay) which is required. Can you please check e.g. network traffic if `RecordReplay` is required with errors.

**Comment by nilskasseckert** [comment]
Thanks for your answer! I think I have found the error.

If I don't navigate or navigate only with browser.goTo, taking screenshots works in principle but I get the following error. I already had an issue about this in another context open with you. [This](https://github.com/js-soft/wdi5/issues/73) is the ticket

If I use browser.url on the other hand the whole WDI5 context is lost. Then I use browser.goTo. This is no problem. Maybe you should only document it.

Unfortunately the SAP UI5 error remains.

This is the error:
```
[0-0] Error in "0: Ich starte die App"
Evaluation failed: Error: sap.ui.test.autowaiter._autoWaiterAsync#extendConfig - No 'inputToValidate' given but it is a mandatory parameter
    at _validate (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/_ParameterValidator.js?eval:6:509)
    at _.validate (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/_ParameterValidator.js?eval:6:371)
    at v (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/autowaiter/_autoWaiterAsync.js?eval:6:1253)
    at Object.e [as extendConfig] (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/autowaiter/_autoWaiterAsync.js?eval:6:466)
    at Function.R.waitForUI5 (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/RecordReplay.js?eval:6:1935)
    at eval (eval at <anonymous> (:20:16), <anonymous>:3:18)
    at eval (eval at <anonymous> (:20:16), <anonymous>:11:12)
    at __puppeteer_evaluation_script__:20:16
    at new Promise (<anonymous>)
    at __puppeteer_evaluation_script__:2:12
Evaluation failed: Error: sap.ui.test.autowaiter._autoWaiterAsync#extendConfig - No 'inputToValidate' given but it is a mandatory parameter
    at _validate (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/_ParameterValidator.js?eval:6:509)
    at _.validate (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/_ParameterValidator.js?eval:6:371)
    at v (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/autowaiter/_autoWaiterAsync.js?eval:6:1253)
    at Object.e [as extendConfig] (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/autowaiter/_autoWaiterAsync.js?eval:6:466)
    at Function.R.waitForUI5 (https://sapui5.hana.ondemand.com/1.60.31/resources/sap/ui/test/RecordReplay.js?eval:6:1935)
    at eval (eval at <anonymous> (:20:16), <anonymous>:3:18)
    at eval (eval at <anonymous> (:20:16), <anonymous>:11:12)
    at __puppeteer_evaluation_script__:20:16
    at __puppeteer_evaluation_script__:2:12
Error: Evaluation failed: Error: sap.ui.test.autowaiter._autoWaiterAsync#extendConfig - No 'inputToValidate' given but it is a mandatory parameter
    at ExecutionContext._evaluateInternal i/node_modules/puppeteer-core/src/common/ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at ExecutionContext.evaluate /node_modules/puppeteer-core/src/common/ExecutionContext.ts:138:12)
    at ElementHandle.evaluate (node_modules/puppeteer-core/src/common/JSHandle.ts:159:12)
    at ElementHandle.$eval (node_modules/puppeteer-core/src/common/JSHandle.ts:820:20)
    at DevToolsDriver.executeAsyncScript (/node_modules/devtools/src/commands/executeAsyncScript.ts:34:20)
    at Browser.wrappedCommand (node_modules/devtools/src/devtoolsdriver.ts:103:26)
    at _checkForUI5Ready (node_modules/wdio-ui5-service/src/lib/wdioUi5-index.js:517:33)

**Comment by nilskasseckert** [comment]
Hi Volker,
Why Closed? The Error is still there.

Regards, 
Nils

**Comment by dominikfeininger** [comment]
Hi, in ui5 version 1.60.* some test features work differently than in ^1.80.* Can you please check with a more recent UI5 version.

**Comment by nilskasseckert** [comment]
Yes as mentioned before. This is the ticket form February this year on this repository: https://github.com/js-soft/wdi5/issues/73 

This is an bug. There was a bug in the selector but @vobu fixed them. The same bug now occurs in the screen recorder. 

The problem is our company uses currently version 1.60.31 and later this year 1.71.25 as 1.71.25 is the latest release for FES on Prem. This two versions have both the same issue.
